spring:
  profiles:
    default: local
  banner:
    location: common/banner.txt
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

---
spring.config.activate.on-profile: local
server:
  port: 8081
---
spring.config.activate.on-profile: prod