name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: variables
        run: |
          echo "GITHUB.REPOSITORY_OWNER: {{ github.repository_owner }}"
          echo "GITHUB.SHA: {{ github.sha }}"
          echo "SECRETS.GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "SECRETS.GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}"

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: ./gradlew :ujon-api:build

      - name: Build jar
        if: success()
        run: ./gradlew :ujon-api:bootJar

      - name: Upload jar as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ujon-api-jar
          path: |
            ujon-api/build/libs/
            ujon-api/Dockerfile

  packaging:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: build
    steps:
      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: ujon-api-jar
          path: ujon-api/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: docker build -f ./ujon-api/Dockerfile -t ghcr.io/${{ github.repository_owner }}/ujon-api:${{ github.sha }} .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/ujon-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: packaging
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ujon.dev
          username: ujon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export PATH="/usr/local/bin:$PATH"
            echo "{\"auths\": { \"ghcr.io\": { \"username\": \"${{ github.repository_owner }}\", \"password\": \"${{ secrets.GHCR_TOKEN }}\" } } }" > ~/.docker/config.json
            docker pull ghcr.io/${{ github.repository_owner }}/ujon-api:${{ github.sha }}
            docker run -d --name ujon-api -p 8081:8081 ghcr.io/${{ github.repository_owner }}/ujon-api:${{ github.sha }}



